/* ─── Haikyuu!! Data ─────────────────────────────── */

const TEAMS = {
  karasuno:    { name: 'Karasuno High',       name_jp: '烏野高校',         color: '#F26522', short: 'KRS', motto: 'Flightless Crows' },
  aoba:        { name: 'Aoba Johsai High',    name_jp: '青葉城西高校',     color: '#1B8CCC', short: 'AJO', motto: 'King of the Court' },
  nekoma:      { name: 'Nekoma High',         name_jp: '音駒高校',         color: '#CC1F2B', short: 'NKM', motto: 'Connect' },
  fukurodani:  { name: 'Fukurodani Academy',  name_jp: '梟谷学園',         color: '#2D2D2D', short: 'FKD', motto: 'Onomatopoeia' },
  shiratoriz:  { name: 'Shiratorizawa Acad.', name_jp: '白鳥沢学園',       color: '#7B3FBE', short: 'SHR', motto: 'The Strong Survive' },
  inarizaki:   { name: 'Inarizaki High',      name_jp: '稲荷崎高校',       color: '#4A4A4A', short: 'INR', motto: 'We Don\'t Need Memories' },
  itachiyama:  { name: 'Itachiyama Institute', name_jp: '伊達工業高校',    color: '#1B4D8E', short: 'ITY', motto: 'The Top' },
  msby:        { name: 'MSBY Black Jackals',  name_jp: 'MSBYブラックジャッカルズ', color: '#F2A600', short: 'MSB', motto: 'Fly High' },
  schweiden:   { name: 'Schweiden Adlers',    name_jp: 'シュワイデン・アドラーズ', color: '#9B59B6', short: 'SCH', motto: 'Strength' },
};

const CHARACTERS = [
  /* ─── Karasuno ───────────────────────────────────── */
  {
    id: 'hinata',
    name: 'Shoyo Hinata',       name_jp: '日向 翔陽',
    team: 'karasuno',           number: 10,
    position: 'Middle Blocker / Wing Spiker',
    height: '162.8 cm',         weight: '51.9 kg',
    birthday: 'June 21',        age: 16,
    blood: 'O',
    school: 'Karasuno High',
    image: 'images/characters/karasuno/hinata.jpg',
    emoji: '🧡',
    color: '#F26522',
    stats: { power: 78, speed: 95, jump: 90, technique: 72, intelligence: 60, stamina: 88 },
    desc: 'ตัวละครหลักของเรื่อง เป็นตัวเล็กแต่กระโดดสูงมาก มีพรสวรรค์พิเศษในเรื่องการรับรู้สนาม เชื่อมือกับ Kageyama จนกลายเป็น "ฟ้าผ่า" ที่น่าเกรงขาม มีความฝันตั้งแต่เด็กที่จะเป็นเหมือน "The Small Giant" ตำนานของ Karasuno',
    quote: '"แม้แค่ขยับตัวนิดเดียวก็ยังดีกว่าหยุดอยู่กับที่!"',
    abilities: ['Quick Strike (ยอดเร็ว)', 'Super Receive', 'Freak Quick Set', 'Block-Out Shot'],
    trivia: 'เป็นคนแรกที่ทำ "Freak Quick" กับ Kageyama สำเร็จ',
  },
  {
    id: 'kageyama',
    name: 'Tobio Kageyama',     name_jp: '影山 飛雄',
    team: 'karasuno',           number: 9,
    position: 'Setter',
    height: '180.6 cm',         weight: '66.3 kg',
    birthday: 'December 22',    age: 16,
    blood: 'A',
    school: 'Karasuno High',
    image: 'images/characters/karasuno/kageyama.jpg',
    emoji: '👑',
    color: '#1B4D8E',
    stats: { power: 75, speed: 80, jump: 78, technique: 96, intelligence: 85, stamina: 82 },
    desc: 'อัจฉริยะด้านการเซต ได้รับฉายาว่า "กษัตริย์แห่งสนาม" จาก Kitagawa Daiichi ก่อนที่จะเข้า Karasuno มีความสามารถในการเซตลูกที่แม่นยำสูงสุด ต่อมาพัฒนาทักษะการทำงานเป็นทีมจนกลายเป็นผู้นำที่แท้จริง',
    quote: '"ถ้าชนะได้คนเดียว ฉันก็ชนะคนเดียวมาแล้ว — แต่ฉันชนะไม่ได้"',
    abilities: ['Freak Quick Set', 'Jump Serve', 'Goat Set', 'Aerial Receive'],
    trivia: 'ได้รับเลือกเป็นตัวแทนทีมชาติญี่ปุ่นหลังจบโรงเรียน',
  },
  {
    id: 'tsukishima',
    name: 'Kei Tsukishima',     name_jp: '月島 蛍',
    team: 'karasuno',           number: 11,
    position: 'Middle Blocker',
    height: '188.3 cm',         weight: '69.0 kg',
    birthday: 'September 27',   age: 16,
    blood: 'AB',
    school: 'Karasuno High',
    image: 'images/characters/karasuno/tsukishima.jpg',
    emoji: '🦖',
    color: '#2D5E1C',
    stats: { power: 72, speed: 60, jump: 74, technique: 80, intelligence: 92, stamina: 70 },
    desc: 'ตัวบล็อคตัวสูงที่ฉลาดที่สุดในทีม ชอบใช้ไม้บล็อคเพื่อรับมือกับ Ace ฝ่ายตรงข้าม มีบุคลิกเย็นชาและชอบแดกดัน แต่ซ่อนความทุ่มเทไว้ข้างใน จุดเปลี่ยนสำคัญคือการบล็อค Ushijima ในแมตช์ Shiratorizawa',
    quote: '"ชัยชนะหรือความพ่ายแพ้... ชีวิตยังดำเนินต่อไปอยู่ดี"',
    abilities: ['Read Blocking', 'Soft Block', 'Net Defense', 'Zone Defense'],
    trivia: 'ชอบไดโนเสาร์มากและมีของสะสมเยอะมาก',
  },
  {
    id: 'nishinoya',
    name: 'Yu Nishinoya',       name_jp: '西谷 夕',
    team: 'karasuno',           number: 4,
    position: 'Libero',
    height: '159.3 cm',         weight: '51.1 kg',
    birthday: 'October 10',     age: 17,
    blood: 'B',
    school: 'Karasuno High',
    image: 'images/characters/karasuno/nishinoya.jpg',
    emoji: '⚡',
    color: '#F2A600',
    stats: { power: 60, speed: 92, jump: 68, technique: 91, intelligence: 74, stamina: 95 },
    desc: '"เทพเจ้าแห่งการรับ" ของ Karasuno มีเทคนิคการรับที่หลากหลายและสร้างสรรค์อย่างยิ่ง เป็น Libero ที่ใช้ทุกส่วนของร่างกายรับลูก ทั้ง Libero Rolling Thunder, Jumping Receive ฯลฯ มีบุคลิกพลังงานสูงและมักแสดงออกด้วยการตะโกน',
    quote: '"Libero ก็บินได้!"',
    abilities: ['Rolling Thunder', 'Jumping Receive', 'Diagonal Receive', 'Jump Setter'],
    trivia: 'ถูกพักโทษ 3 เกมเพราะทะเลาะกับนักเรียนปี 3 เพื่อปกป้อง Asahi',
  },
  {
    id: 'tanaka',
    name: 'Ryunosuke Tanaka',   name_jp: '田中 龍之介',
    team: 'karasuno',           number: 5,
    position: 'Wing Spiker',
    height: '177.2 cm',         weight: '70.4 kg',
    birthday: 'March 3',        age: 17,
    blood: 'B',
    school: 'Karasuno High',
    image: 'images/characters/karasuno/tanaka.jpg',
    emoji: '💪',
    color: '#CC4400',
    stats: { power: 84, speed: 82, jump: 76, technique: 75, intelligence: 68, stamina: 88 },
    desc: 'Wing Spiker ที่มีจิตใจแกร่งที่สุดในทีม ไม่มีวันยอมแพ้ แม้ถูก Block ก็ยังสามารถฝ่าผ่านได้ด้วยพลังจิตใจ มีท่าทาง "ไม่กลัว" ที่เป็นเอกลักษณ์ ตอนหลังแต่งงานกับ Kiyoko Shimizu ในอนาคต',
    quote: '"ฉันจะตีทะลุผ่านไป!"',
    abilities: ['Cross Shot', 'Straight Shot', 'Block Aversion', 'Jump Float Serve'],
    trivia: 'เป็นสมาชิกคณะกรรมการนักเรียนที่พยายามจีบ Kiyoko ตลอด',
  },
  {
    id: 'asahi',
    name: 'Asahi Azumane',      name_jp: '東峰 旭',
    team: 'karasuno',           number: 3,
    position: 'Wing Spiker / Ace',
    height: '184.7 cm',         weight: '75.2 kg',
    birthday: 'January 1',      age: 18,
    blood: 'A',
    school: 'Karasuno High',
    image: 'images/characters/karasuno/asahi.jpg',
    emoji: '🦁',
    color: '#8B5E3C',
    stats: { power: 92, speed: 68, jump: 80, technique: 78, intelligence: 72, stamina: 76 },
    desc: 'Ace ของ Karasuno ที่มีรูปร่างน่าเกรงขามและโกนหนวดเหลือไว้ แต่จริงๆ แล้วจิตใจอ่อนไหวมาก เป็นตัวละครที่เติบโตมากที่สุดในเรื่องเพราะต้องเอาชนะความกลัวและความสงสัยในตัวเองซ้ำแล้วซ้ำเล่า',
    quote: '"ถ้า Spiker ไม่เจาะ Block ได้ ก็ต้องหาทางอื่น"',
    abilities: ['Cross Shot Power', 'Back Attack', 'Block Aversion Spike', 'Wrist Shot'],
    trivia: 'ผมยาวมัดไว้เพราะขี้เกียจตัดผม ไม่ใช่เพราะสไตล์',
  },
  {
    id: 'daichi',
    name: 'Daichi Sawamura',    name_jp: '澤村 大地',
    team: 'karasuno',           number: 1,
    position: 'Wing Spiker / Captain',
    height: '176.7 cm',         weight: '70.4 kg',
    birthday: 'December 31',    age: 18,
    blood: 'A',
    school: 'Karasuno High',
    image: 'images/characters/karasuno/daichi.jpg',
    emoji: '🛡',
    color: '#2C6E49',
    stats: { power: 80, speed: 76, jump: 72, technique: 80, intelligence: 86, stamina: 90 },
    desc: 'กัปตันและหัวใจของ Karasuno ผู้นำที่แข็งแกร่งทั้งร่างกายและจิตใจ มีทักษะการรับที่ยอดเยี่ยมสำหรับ Wing Spiker รู้จักอ่านเกมและควบคุมทีมในสถานการณ์ยากลำบาก มักถูกมองว่า "หน้าเหี้ยม" แต่จริงๆ ใจดีมาก',
    quote: '"พวกเราจะไม่แพ้ใครง่ายๆ"',
    abilities: ['Serve Receive', 'Powerful Spike', 'Team Leadership', 'Reading Opponent'],
    trivia: 'ต่อมาเป็นตำรวจในตอนจบเรื่อง',
  },
  {
    id: 'sugawara',
    name: 'Koushi Sugawara',    name_jp: '菅原 孝支',
    team: 'karasuno',           number: 2,
    position: 'Setter',
    height: '172.9 cm',         weight: '63.5 kg',
    birthday: 'June 13',        age: 18,
    blood: 'AB',
    school: 'Karasuno High',
    image: 'images/characters/karasuno/sugawara.jpg',
    emoji: '🌟',
    color: '#5B8CC8',
    stats: { power: 65, speed: 70, jump: 70, technique: 85, intelligence: 90, stamina: 80 },
    desc: 'Setter สำรองของ Karasuno ที่เก่งมากแต่ถูกแซงโดย Kageyama ความพิเศษของ Suga คือ IQ วอลเลย์บอลที่สูงมาก เขาใช้เทคนิคและกลยุทธ์แทนพลังดิบ สามารถอ่านผู้เล่นแต่ละคนได้อย่างแม่นยำ',
    quote: '"ผมยังอยู่ในสนาม ผมยังเล่นอยู่"',
    abilities: ['Deceptive Set', 'Float Serve', 'Ace Setting', 'Pinch Hitting'],
    trivia: 'เป็นครูในตอนจบ — สะท้อนบุคลิกผู้สอนและสนับสนุนคนอื่น',
  },
  {
    id: 'yamaguchi',
    name: 'Tadashi Yamaguchi',  name_jp: '山口 忠',
    team: 'karasuno',           number: 12,
    position: 'Middle Blocker / Pinch Server',
    height: '179.5 cm',         weight: '67.3 kg',
    birthday: 'November 10',    age: 16,
    blood: 'AB',
    school: 'Karasuno High',
    image: 'images/characters/karasuno/yamaguchi.jpg',
    emoji: '🎯',
    color: '#5E8A3C',
    stats: { power: 65, speed: 65, jump: 70, technique: 86, intelligence: 80, stamina: 72 },
    desc: 'เพื่อนสนิทของ Tsukishima ตั้งแต่เด็ก เชี่ยวชาญ Float Jump Serve ที่ควบคุมได้ยากมาก มีพัฒนาการที่น่าประทับใจ จากผู้เล่นตัวสำรองที่ไม่มั่นใจในตัวเอง กลายเป็น Pinch Server ที่อันตรายและต่อมาเป็นกัปตันทีม',
    quote: '"ฉันจะพัฒนาตัวเองให้ดีขึ้นเรื่อยๆ"',
    abilities: ['Jump Float Serve', 'Middle Block', 'Pinch Serve'],
    trivia: 'ขอ Tsukki ฝึกเซิร์ฟด้วยกัน จนกลายเป็นอาวุธหลักของทีม',
  },
  /* ─── Aoba Johsai ────────────────────────────────── */
  {
    id: 'oikawa',
    name: 'Tooru Oikawa',       name_jp: '及川 徹',
    team: 'aoba',               number: 1,
    position: 'Setter / Captain',
    height: '184.3 cm',         weight: '72.2 kg',
    birthday: 'July 20',        age: 18,
    blood: 'B',
    school: 'Aoba Johsai High',
    image: 'images/characters/aoba-johsai/oikawa.jpg',
    emoji: '👁',
    color: '#1B8CCC',
    stats: { power: 78, speed: 80, jump: 78, technique: 95, intelligence: 96, stamina: 82 },
    desc: 'Setter คนที่ฉลาดที่สุดในเรื่อง มีความสามารถในการดึงศักยภาพสูงสุดจากผู้เล่นทุกคน ฝึกซ้อมอย่างหนักจนเอาชนะข้อจำกัดของพรสวรรค์ ต่อมาย้ายไปเล่นวอลเลย์บอลอาชีพในอาร์เจนตินา',
    quote: '"พรสวรรค์เป็นสิ่งที่น่าอัปยศถ้าไม่ทุ่มเทฝึกซ้อม"',
    abilities: ['Serve (Strongest in Miyagi)', 'Precision Set', 'Read Opponent', 'Jump Serve'],
    trivia: 'อิจฉา Kageyama มากแต่ยอมรับว่าเป็นคู่ปรับที่ทำให้ตัวเองเก่งขึ้น',
  },
  {
    id: 'iwaizumi',
    name: 'Hajime Iwaizumi',    name_jp: '岩泉 一',
    team: 'aoba',               number: 4,
    position: 'Wing Spiker / Ace',
    height: '179.3 cm',         weight: '70.0 kg',
    birthday: 'June 10',        age: 18,
    blood: 'O',
    school: 'Aoba Johsai High',
    image: 'images/characters/aoba-johsai/iwaizumi.jpg',
    emoji: '🔥',
    color: '#2C3E7A',
    stats: { power: 90, speed: 78, jump: 80, technique: 84, intelligence: 82, stamina: 86 },
    desc: 'Ace ของ Aoba Johsai และเพื่อนสนิทของ Oikawa ตั้งแต่เด็ก มีพลังตีที่แรงมาก ต่อมาเป็น Athletic Trainer สำหรับทีมกีฬามืออาชีพในอเมริกา',
    quote: '"Oikawa โง่จริงๆ แต่เขาไม่ใช่คนอ่อนแอ"',
    abilities: ['Powerful Cross Shot', 'Serve', 'Back Attack', 'Straight Shot'],
    trivia: 'Iwa-chan เป็นชื่อเล่นที่ Oikawa ชอบใช้เรียก',
  },
  /* ─── Nekoma ─────────────────────────────────────── */
  {
    id: 'kuroo',
    name: 'Tetsurou Kuroo',     name_jp: '黒尾 鉄朗',
    team: 'nekoma',             number: 1,
    position: 'Middle Blocker / Captain',
    height: '187.7 cm',         weight: '75.3 kg',
    birthday: 'November 17',    age: 18,
    blood: 'O',
    school: 'Nekoma High',
    image: 'images/characters/nekoma/kuroo.jpg',
    emoji: '🐈',
    color: '#CC1F2B',
    stats: { power: 82, speed: 76, jump: 82, technique: 84, intelligence: 90, stamina: 80 },
    desc: 'กัปตัน Nekoma และอาจารย์บล็อคของ Tsukishima ผู้ที่ช่วยให้ Tsukki ค้นพบความหมายของวอลเลย์บอล มีผมยุ่งเหมือนแมวตื่นนอน ต่อมาทำงานด้านกีฬาในฝ่ายพัฒนาของ JVBA',
    quote: '"ทุกทีมต่างก็มีจุดอ่อน ค้นหามันให้เจอ แล้วโจมตีซ้ำๆ"',
    abilities: ['Roof Block', 'Read Block', 'Slide Attack', 'Leadership'],
    trivia: 'มีผมยุ่งเพราะตื่นนอนมาแบบนั้น ไม่ได้จงใจทำ',
  },
  {
    id: 'kenma',
    name: 'Kenma Kozume',       name_jp: '孤爪 研磨',
    team: 'nekoma',             number: 5,
    position: 'Setter',
    height: '169.2 cm',         weight: '59.0 kg',
    birthday: 'October 16',     age: 17,
    blood: 'AB',
    school: 'Nekoma High',
    image: 'images/characters/nekoma/kenma.jpg',
    emoji: '🎮',
    color: '#D4AC0D',
    stats: { power: 55, speed: 70, jump: 58, technique: 90, intelligence: 99, stamina: 55 },
    desc: 'อัจฉริยะด้านกลยุทธ์ที่มองวอลเลย์บอลเหมือนเกม ไม่ชอบออกแรงมากเกินจำเป็น แต่มีความสามารถในการวิเคราะห์คู่แข่งได้อย่างแม่นยำ ต่อมากลายเป็น YouTuber/Streamer เกมดัง',
    quote: '"ฉันไม่ชอบแพ้ มันทำให้เหนื่อย"',
    abilities: ['Precision Setter', 'Game Reading', 'Deceptive Set', 'Low Stamina Strategy'],
    trivia: 'เล่นเกมทุกวัน เป็นเกมเมอร์ตัวยง Hinata เป็นเพื่อนที่เขาชอบที่สุด',
  },
  /* ─── Fukurodani ─────────────────────────────────── */
  {
    id: 'bokuto',
    name: 'Kotaro Bokuto',      name_jp: '木兔 光太郎',
    team: 'fukurodani',         number: 4,
    position: 'Wing Spiker / Ace / Captain',
    height: '185.5 cm',         weight: '78.0 kg',
    birthday: 'September 20',   age: 18,
    blood: 'O',
    school: 'Fukurodani Academy',
    image: 'images/characters/fukurodani/bokuto.jpg',
    emoji: '🦉',
    color: '#2D2D2D',
    stats: { power: 96, speed: 80, jump: 88, technique: 90, intelligence: 70, stamina: 90 },
    desc: 'Top 5 Ace ของญี่ปุ่น ผู้เล่นที่มีพลังเหลือเชื่อแต่จิตใจอ่อนไหวง่าย มักตกอยู่ใน "Emo Mode" เมื่อเจอเหตุการณ์กดดัน แต่เมื่อ "อยู่ในสภาวะสูงสุด" จะกลายเป็นผู้เล่นที่น่าเกรงขามที่สุด',
    quote: '"HEY HEY HEY!"',
    abilities: ['Overhand Spike', 'Wrist Shot', 'Block Follow', 'Rebound Shot'],
    trivia: 'Top 5 Aces ในญี่ปุ่น ต่อมาเล่นให้ MSBY Black Jackals พร้อมกับ Hinata',
  },
  {
    id: 'akaashi',
    name: 'Keiji Akaashi',      name_jp: '赤葦 京治',
    team: 'fukurodani',         number: 5,
    position: 'Setter',
    height: '182.3 cm',         weight: '67.4 kg',
    birthday: 'December 5',     age: 17,
    blood: 'A',
    school: 'Fukurodani Academy',
    image: 'images/characters/fukurodani/akaashi.jpg',
    emoji: '📚',
    color: '#556B8C',
    stats: { power: 72, speed: 76, jump: 76, technique: 88, intelligence: 94, stamina: 76 },
    desc: 'Setter ที่ฉลาดและใจเย็น ทำหน้าที่ดูแล Bokuto อยู่ตลอดเวลา รู้จักรูปแบบ "Emo Mode" ของ Bokuto 37 แบบ ต่อมาเป็นบรรณาธิการหนังสือ',
    quote: '"Bokuto-san ผมจะยิงลูกที่ดีที่สุดให้คุณ"',
    abilities: ['Precision Set', 'Quick Set', 'Anti-Emo Mode Tactics', 'Reading Players'],
    trivia: 'รู้จักวิธีดึง Bokuto ออกจาก Emo Mode ทุกแบบ',
  },
  /* ─── Shiratorizawa ──────────────────────────────── */
  {
    id: 'ushijima',
    name: 'Wakatoshi Ushijima',  name_jp: '牛島 若利',
    team: 'shiratoriz',          number: 1,
    position: 'Wing Spiker / Ace / Captain',
    height: '189.5 cm',          weight: '84.8 kg',
    birthday: 'August 13',       age: 18,
    blood: 'B',
    school: 'Shiratorizawa Acad.',
    image: 'images/characters/shiratorizawa/ushijima.jpg',
    emoji: '🦅',
    color: '#7B3FBE',
    stats: { power: 99, speed: 72, jump: 86, technique: 88, intelligence: 80, stamina: 88 },
    desc: 'Top 3 Ace ของญี่ปุ่น ผู้เล่นซ้ายมือที่มีพลังตีสูงสุด เล่นด้วยรูปแบบง่ายๆ "ชนะด้วยพลัง" ไม่มีความสลับซับซ้อน แต่ยากมากที่จะรับ ต่อมาเป็นนักวอลเลย์บอลอาชีพในต่างประเทศ',
    quote: '"คนที่เก่งกว่าย่อมชนะ"',
    abilities: ['Left-Hand Spike (Most Powerful)', 'Jump Serve', 'Straight Shot', 'Top Spin'],
    trivia: 'เป็น Left-hander ซึ่งทำให้การรับลูกของเขาแตกต่างจากปกติมาก',
  },
  {
    id: 'tendou',
    name: 'Satori Tendou',      name_jp: '天童 覚',
    team: 'shiratoriz',         number: 5,
    position: 'Middle Blocker',
    height: '187.7 cm',         weight: '71.0 kg',
    birthday: 'May 20',         age: 18,
    blood: 'O',
    school: 'Shiratorizawa Acad.',
    image: 'images/characters/shiratorizawa/tendou.jpg',
    emoji: '😈',
    color: '#E74C3C',
    stats: { power: 74, speed: 72, jump: 80, technique: 80, intelligence: 88, stamina: 76 },
    desc: '"Guess Monster" ผู้มีความสามารถพิเศษในการเดาทิศทางการสไปค์ของฝ่ายตรงข้าม มักถูกรังแกตั้งแต่เด็กจนพัฒนาบุคลิกแปลกๆ แต่ Ushijima เป็นคนที่ทำให้เขายืนหยัดได้',
    quote: '"ฉันคือ Guess Monster!"',
    abilities: ['Guess Block', 'Read Block', 'Quick Spike', 'Intimidation'],
    trivia: 'ตอนจบไปฝึกทำพาสต้าในฝรั่งเศส',
  },
  /* ─── Inarizaki ──────────────────────────────────── */
  {
    id: 'atsumu',
    name: 'Atsumu Miya',        name_jp: '宮 侑',
    team: 'inarizaki',          number: 11,
    position: 'Setter',
    height: '183.1 cm',         weight: '73.1 kg',
    birthday: 'October 5',      age: 16,
    blood: 'O',
    school: 'Inarizaki High',
    image: 'images/characters/inarizaki/atsumu.jpg',
    emoji: '🌊',
    color: '#4A4A4A',
    stats: { power: 80, speed: 82, jump: 82, technique: 97, intelligence: 86, stamina: 82 },
    desc: 'Setter อัจฉริยะที่มีความสามารถพิเศษในการ Serve ทั้ง Jump Float และ Jump Spike Serve ที่แม่นยำมาก มีบุคลิกชอบแก่งแย่งกับพี่น้อง ต่อมาเป็น Setter ของ MSBY Black Jackals',
    quote: '"เราไม่ต้องการความทรงจำ เราต้องการชัยชนะ"',
    abilities: ['Jump Float Serve', 'Setter Dump', 'Precision Set', 'Barrier Jump Serve'],
    trivia: 'แกล้ง Hinata ก่อนตัดสินใจรับเขาเข้าทีม MSBY',
  },
  {
    id: 'osamu',
    name: 'Osamu Miya',         name_jp: '宮 治',
    team: 'inarizaki',          number: 10,
    position: 'Wing Spiker',
    height: '180.6 cm',         weight: '72.6 kg',
    birthday: 'October 5',      age: 16,
    blood: 'O',
    school: 'Inarizaki High',
    image: 'images/characters/inarizaki/osamu.jpg',
    emoji: '🍱',
    color: '#5A5A5A',
    stats: { power: 80, speed: 76, jump: 78, technique: 82, intelligence: 82, stamina: 80 },
    desc: 'พี่น้องฝาแฝดของ Atsumu ใจเย็นกว่าพี่น้องมาก เก่งวอลเลย์บอลมากแต่ตัดสินใจเลิกเล่นอาชีพหลังจบม.ปลาย และเปิดร้านข้าวปั้น onigiri ที่ประสบความสำเร็จ',
    quote: '"ฉันมีพรสวรรค์เหมือนกัน แค่ไม่ได้ใช้มันแบบเดียวกัน"',
    abilities: ['Powerful Spike', 'Back Attack', 'Receive', 'Dummy Attack'],
    trivia: 'เปิดร้าน Onigiri Miya ที่ดังมากในตอนจบ',
  },
  {
    id: 'suna',
    name: 'Rintaro Suna',       name_jp: '角名 倫太郎',
    team: 'inarizaki',          number: 13,
    position: 'Middle Blocker',
    height: '187.1 cm',         weight: '73.2 kg',
    birthday: 'January 25',     age: 16,
    blood: 'B',
    school: 'Inarizaki High',
    image: 'images/characters/inarizaki/suna.jpg',
    emoji: '🎥',
    color: '#3D3D3D',
    stats: { power: 80, speed: 72, jump: 80, technique: 86, intelligence: 84, stamina: 76 },
    desc: 'Middle Blocker ที่มีเทคนิคการตีในช่องว่างที่แคบมาก มักถ่ายวิดีโอพี่น้อง Miya ทะเลาะกัน ต่อมาเป็นนักวอลเลย์บอลอาชีพในเยอรมนี',
    quote: '"...(เฉยๆ)"',
    abilities: ['Gap Shot', 'Angle Spike', 'Middle Block', 'Timing Spike'],
    trivia: 'ชอบถ่ายวิดีโอพี่น้อง Miya ทะเลาะกันเพื่อดูเล่น',
  },
  /* ─── Others ─────────────────────────────────────── */
  {
    id: 'sakusa',
    name: 'Kiyoomi Sakusa',     name_jp: '佐久早 聖臣',
    team: 'itachiyama',         number: 0,
    position: 'Wing Spiker / Ace',
    height: '189.4 cm',         weight: '80.3 kg',
    birthday: 'March 2',        age: 18,
    blood: 'AB',
    school: 'Itachiyama Institute',
    image: 'images/characters/others/sakusa.jpg',
    emoji: '😷',
    color: '#1B4D8E',
    stats: { power: 90, speed: 80, jump: 84, technique: 94, intelligence: 86, stamina: 84 },
    desc: 'Top 3 Ace ของญี่ปุ่น มีเทคนิคการตีที่ซับซ้อน Top Spin ที่แม่นยำมาก มีนิสัยรักความสะอาดสูงมาก ต่อมาเป็น MSBY Black Jackals ร่วมกับ Hinata',
    quote: '"อย่าเข้ามาใกล้ฉัน"',
    abilities: ['Curve Shot', 'Top Spin', 'Wrist Control', 'Jump Serve'],
    trivia: 'มี OCD เรื่องความสะอาด ไม่ชอบให้ใครมาใกล้',
  },
  {
    id: 'lev',
    name: 'Lev Haiba',          name_jp: '灰羽 リエーフ',
    team: 'nekoma',             number: 11,
    position: 'Middle Blocker',
    height: '194.3 cm',         weight: '80.0 kg',
    birthday: 'October 30',     age: 16,
    blood: 'A',
    school: 'Nekoma High',
    image: 'images/characters/nekoma/lev.jpg',
    emoji: '🐱',
    color: '#5D7A8C',
    stats: { power: 78, speed: 64, jump: 82, technique: 62, intelligence: 60, stamina: 76 },
    desc: 'ลูกครึ่งญี่ปุ่น-รัสเซีย ตัวสูงที่สุดในทีม เพิ่งเริ่มวอลเลย์บอลแต่มีพรสวรรค์มหาศาล มีบุคลิกร่าเริงและมั่นใจในตัวเองสูงมากจนบางครั้งน่ารำคาญ',
    quote: '"ฉันจะเป็น Ace ของ Nekoma!"',
    abilities: ['Height Advantage Block', 'Quick Spike', 'Receive (ยังอ่อน)', 'Long Reach'],
    trivia: 'พี่สาวชื่อ Alisa เป็นนางแบบ มีเลือดรัสเซีย',
  },
];

const TIMELINE = [
  {
    arc: 'ก่อนเรื่องจะเริ่ม',
    title: 'The Small Giant',
    year: '2012',
    desc: 'Hinata ชม Karasuno ใน Inter-High เป็นครั้งแรก และตกหลุมรักวอลเลย์บอลจากการเห็น The Small Giant',
    result: 'event',
  },
  {
    arc: 'Intro Arc',
    title: 'Hinata เข้า Karasuno',
    year: '2012 เมษา',
    desc: 'Hinata เริ่มมัธยมปลาย พบ Kageyama เป็นครั้งแรกในฐานะคู่แข่ง และบังคับให้เล่นด้วยกัน กำเนิด "Freak Quick"',
    result: 'event',
  },
  {
    arc: 'Interhigh Qualifier',
    title: 'vs Aoba Johsai (Round 1)',
    year: 'เมษายน 2012',
    desc: 'แมตช์แรกกับ Oikawa และ Aoba Johsai ทีมอยู่ในระดับที่ต่างกันมาก Karasuno แพ้ชัดเจน แต่แสดงศักยภาพ Freak Quick ออกมาได้',
    result: 'loss',
    score: '0-2'
  },
  {
    arc: 'Tokyo Training Camp',
    title: 'Fukurodani & Nekoma Training Camp',
    year: 'สิงหาคม 2012',
    desc: 'Karasuno ฝึกซ้อมกับทีมโตเกียวรวมถึง Fukurodani, Nekoma, Ubugawa กระตุ้นการพัฒนาของ Tsukishima เรื่อง Blocking',
    result: 'event',
  },
  {
    arc: 'Spring High Qualifier',
    title: 'vs Aoba Johsai (คู่ปรับ)',
    year: 'ตุลาคม 2012',
    desc: 'แมตช์สำคัญที่ Karasuno แก้แค้น Aoba Johsai ได้สำเร็จหลังจาก Hinata กลับมาจากการบาดเจ็บ',
    result: 'win',
    score: '2-1'
  },
  {
    arc: 'Spring High Qualifier',
    title: 'vs Shiratorizawa',
    year: 'ตุลาคม 2012',
    desc: 'แมตช์มหากาพย์ 5 เซต Karasuno ต้องเอาชนะ Ushijima และ Tendou Tsukishima บล็อค Ushijima ได้สำเร็จ 1 จุดที่สำคัญ',
    result: 'win',
    score: '3-2'
  },
  {
    arc: 'Spring High National',
    title: 'Nationals — เดินทางสู่โตเกียว',
    year: 'มกราคม 2013',
    desc: 'Karasuno ผ่านเข้ารอบ National Spring Tournament เป็นครั้งแรกในรอบหลายปี ทีมเดินทางสู่โตเกียว',
    result: 'event',
  },
  {
    arc: 'Spring High National',
    title: 'vs Inarizaki (พี่น้อง Miya)',
    year: 'มกราคม 2013',
    desc: 'แมตช์ที่เต็มไปด้วยความตื่นเต้น พี่น้อง Miya vs Karasuno Hinata พัฒนา Serve Receive ในระหว่างแมตช์',
    result: 'win',
    score: '2-1'
  },
  {
    arc: 'Spring High National',
    title: 'vs Nekoma — "Garbage Dump Match"',
    year: 'มกราคม 2013',
    desc: 'แมตช์ที่แฟนๆ รอคอยมานาน "Karasuno vs Nekoma" การเผชิญหน้าของ "Cats vs Crows" ที่กำหนดชะตาของทั้งสองทีม',
    result: 'win',
    score: '2-1'
  },
  {
    arc: 'Spring High National',
    title: 'vs Kamomedai — ความพ่ายแพ้',
    year: 'มกราคม 2013',
    desc: 'Karasuno พบกับ Blocker ที่เชี่ยวชาญมากที่สุด Hinata ล้มป่วยและต้องออกจากสนาม แพ้ในที่สุด',
    result: 'loss',
    score: '0-2'
  },
  {
    arc: 'Time Skip',
    title: 'หลังจบมัธยมปลาย',
    year: '2013 เป็นต้นไป',
    desc: 'ตัวละครแยกย้ายไปตามเส้นทางของตัวเอง Hinata ไปฝึกวอลเลย์บอลในบราซิล Kageyama เป็นตัวแทนทีมชาติ',
    result: 'event',
  },
  {
    arc: 'Epilogue',
    title: 'MSBY vs Schweiden Adlers',
    year: '2018',
    desc: 'แมตช์ฝันที่ Hinata (MSBY) กลับมาเจอ Ushijima & Kageyama (Schweiden Adlers) ในระดับ V-League อาชีพ',
    result: 'event',
  },
];

const TRIVIA = [
  {
    num: '01',
    category: 'ข้อเท็จจริง',
    title: 'ชื่อตัวละครมีความหมาย',
    body: '"Hinata" (日向) แปลว่า "ที่ที่แสงแดดส่องถึง" สะท้อนบุคลิกสดใสของเขา ส่วน "Kageyama" (影山) แปลว่า "ภูเขาเงา" — ตรงข้ามกันพอดีกับ Hinata ที่เป็น "แสงสว่าง"',
    icon: '📖'
  },
  {
    num: '02',
    category: 'การออกแบบ',
    title: 'Haruichi Furudate เป็นผู้หญิง',
    body: 'หลายคนไม่ทราบว่าผู้แต่ง Haikyuu!! เป็นผู้หญิง ฉลาดในการออกแบบตัวละครชายให้มีมิติหลากหลายและสมจริงมาก',
    icon: '✏️'
  },
  {
    num: '03',
    category: 'กีฬา',
    title: 'เทคนิควอลเลย์บอลในเรื่องถูกต้องตามความเป็นจริง',
    body: '"Freak Quick" หรือการตีลูกเร็วพิเศษ มีในวอลเลย์บอลจริง เรียกว่า "Quick Ball Attack" ผู้แต่งค้นคว้าข้อมูลจากนักวอลเลย์บอลอาชีพจริงๆ',
    icon: '🏐'
  },
  {
    num: '04',
    category: 'ตัวเลข',
    title: 'Haikyuu!! ขายได้กว่า 60 ล้านเล่ม',
    body: 'ณ ปี 2023 Haikyuu!! มียอดจำหน่าย Manga รวมกว่า 60 ล้านเล่มทั่วโลก ทำให้เป็นหนึ่งใน Manga กีฬาที่ขายดีที่สุดตลอดกาล',
    icon: '📊'
  },
  {
    num: '05',
    category: 'การผลิต',
    title: 'Production I.G. ทำ Anime ซีซัน 1-4',
    body: 'Anime สี่ซีซันแรกผลิตโดย Production I.G. ซึ่งขึ้นชื่อเรื่องการทำ Sport Anime คุณภาพสูง แต่ Movie Arc สุดท้ายผลิตโดย Production I.G. ร่วมกับ ENGI',
    icon: '🎬'
  },
  {
    num: '06',
    category: 'ตัวละคร',
    title: '"The Small Giant" คือใคร?',
    body: 'Korai Hoshiumi คือ The Small Giant รุ่นใหม่ที่ Hinata ต้องเผชิญ ส่วน Small Giant ตัวจริงที่ Hinata ได้แรงบันดาลใจคือ Tenma Udai ซึ่งเปิดเผยชื่อในตอนท้ายของ Manga',
    icon: '⭐'
  },
  {
    num: '07',
    category: 'สถิติ',
    title: 'Hinata กระโดดสูงแค่ไหน?',
    body: 'Hinata กระโดดได้สูงถึง 333 cm (Spike Height) แม้จะสูงแค่ 162 cm ซึ่งสูงกว่าผู้เล่นที่ตัวสูง 180+ หลายคนในเรื่อง',
    icon: '📏'
  },
  {
    num: '08',
    category: 'ดนตรี',
    title: 'Opening Theme ที่โด่งดัง',
    body: '"Fly High!!" โดย BURNOUT SYNDROMES (Opening ซีซัน 2) และ "Imagination" (Opening ซีซัน 4) ได้รับความนิยมสูงมากในหมู่แฟนๆ ทั่วโลก',
    icon: '🎵'
  },
  {
    num: '09',
    category: 'ความสัมพันธ์',
    title: 'Karasuno vs Nekoma — ตำนานที่รอคอย',
    body: '"Karasuno vs Nekoma" หรือ "Garbage Dump Match" ถูกวางแผนมาตั้งแต่ต้นเรื่อง แฟนๆ รอคอยแมตช์นี้นานหลายปีก่อนจะเกิดขึ้นในตอนท้าย',
    icon: '🐦'
  },
  {
    num: '10',
    category: 'อนาคต',
    title: 'Time Skip ในตอนจบ',
    body: 'Manga จบด้วย Time Skip ข้ามไป 6 ปี ตัวละครหลักได้ติดตามทีมชาติญี่ปุ่น, เป็นนักกีฬาอาชีพ, และ Hinata กลับมาจากบราซิล ทำความฝันสำเร็จ',
    icon: '🔮'
  },
  {
    num: '11',
    category: 'วัฒนธรรม',
    title: 'กระตุ้นความนิยมวอลเลย์บอลในญี่ปุ่น',
    body: 'หลัง Haikyuu!! ออกอากาศ ยอดสมัครเล่นวอลเลย์บอลในโรงเรียนมัธยมของญี่ปุ่นเพิ่มขึ้นอย่างเห็นได้ชัด Manga มีอิทธิพลต่อกีฬาจริงๆ',
    icon: '🇯🇵'
  },
  {
    num: '12',
    category: 'การ์ตูน',
    title: 'Manga ลงใน Weekly Shonen Jump 8 ปี',
    body: 'Haikyuu!! ลงใน Weekly Shonen Jump ตั้งแต่ปี 2012 ถึง 2020 รวม 402 ตอน 45 เล่ม เป็นหนึ่งใน Manga ที่ยาวนานที่สุดของ Jump',
    icon: '📰'
  },
];

// Export for use in other files
if (typeof module !== 'undefined') {
  module.exports = { TEAMS, CHARACTERS, TIMELINE, TRIVIA };
}
